name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:  #  Esta seção é OBRIGATÓRIA
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci  #  Use 'ci' em vez de 'install' para builds mais consistentes
        
      - name: Build project
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'  # Certifique-se que esta pasta existe após o build
          
      - name: Deploy to GitHub Pages
        id: deployment  # Adicione um ID para referência
        uses: actions/deploy-pages@v4